const Vehicle = require("../vehicle/model");
const GpsDevice = require("../gpsDevice/model");
const Driver = require("../drivers/model");
const Organization = require("../organizations/model");
const User = require("../users/model");
const DeviceMapping = require("../deviceMapping/model");
const VehicleDriverMapping = require("../vehicleDriverMapping/model");

const ENTITY_CONFIGS = {
  organizations: {
    entity: "organizations",
    label: "organizations",
    importFields: [
      "name",
      "organizationType",
      "email",
      "phone",
      "addressLine",
      "city",
      "state",
      "country",
      "pincode",
      "parentOrganizationId",
      "parentOrganizationName",
      "status",
    ],
    requiredFields: ["name", "organizationType", "email", "phone"],
    requiredFieldGroups: [],
    headerAliases: {
      name: "name",
      organizationtype: "organizationType",
      type: "organizationType",
      email: "email",
      phone: "phone",
      mobilenumber: "phone",
      mobile: "phone",
      addressline: "addressLine",
      address: "addressLine",
      city: "city",
      state: "state",
      country: "country",
      pincode: "pincode",
      zipcode: "pincode",
      postalcode: "pincode",
      parentorganizationid: "parentOrganizationId",
      parentorganizationname: "parentOrganizationName",
      parentname: "parentOrganizationName",
      status: "status",
    },
    export: {
      filename: "organizations-export",
      headers: [
        "name",
        "organizationType",
        "email",
        "phone",
        "addressLine",
        "city",
        "state",
        "country",
        "pincode",
        "parentOrganizationName",
        "status",
      ],
      model: Organization,
      populate: [{ path: "parentOrganizationId", select: "name" }],
      mapDocument: (doc) => ({
        name: doc.name || "",
        organizationType: doc.organizationType || "",
        email: doc.email || "",
        phone: doc.phone || "",
        addressLine: doc.address?.addressLine || "",
        city: doc.address?.city || "",
        state: doc.address?.state || "",
        country: doc.address?.country || "",
        pincode: doc.address?.pincode || "",
        parentOrganizationName: doc.parentOrganizationId?.name || "",
        status: doc.status || "",
      }),
    },
  },
  users: {
    entity: "users",
    label: "users",
    importFields: [
      "organizationId",
      "organizationName",
      "firstName",
      "lastName",
      "email",
      "mobile",
      "role",
      "status",
      "password",
    ],
    requiredFields: ["firstName", "email", "mobile", "role", "password"],
    requiredFieldGroups: ["organization"],
    headerAliases: {
      organizationid: "organizationId",
      organizationname: "organizationName",
      firstname: "firstName",
      lastname: "lastName",
      email: "email",
      mobile: "mobile",
      phone: "mobile",
      role: "role",
      status: "status",
      password: "password",
      passwordhash: "password",
    },
    export: {
      filename: "users-export",
      headers: [
        "organizationName",
        "firstName",
        "lastName",
        "email",
        "mobile",
        "role",
        "status",
        "createdAt",
      ],
      model: User,
      populate: [{ path: "organizationId", select: "name" }],
      mapDocument: (doc) => ({
        organizationName: doc.organizationId?.name || "",
        firstName: doc.firstName || "",
        lastName: doc.lastName || "",
        email: doc.email || "",
        mobile: doc.mobile || "",
        role: doc.role || "",
        status: doc.status || "",
        createdAt: doc.createdAt ? new Date(doc.createdAt).toISOString() : "",
      }),
    },
  },
  vehicles: {
    entity: "vehicles",
    label: "vehicles",
    importFields: [
      "organizationId",
      "organizationName",
      "vehicleType",
      "vehicleNumber",
      "ais140Compliant",
      "ais140CertificateNumber",
      "make",
      "model",
      "year",
      "color",
      "status",
      "runningStatus",
      "lastUpdated",
      "deviceImei",
    ],
    requiredFields: ["vehicleType", "vehicleNumber"],
    requiredFieldGroups: ["organization"],
    headerAliases: {
      organizationid: "organizationId",
      organizationname: "organizationName",
      vehicletype: "vehicleType",
      type: "vehicleType",
      vehiclenumber: "vehicleNumber",
      registrationnumber: "vehicleNumber",
      registration: "vehicleNumber",
      platenumber: "vehicleNumber",
      ais140compliant: "ais140Compliant",
      ais140certificatenumber: "ais140CertificateNumber",
      make: "make",
      model: "model",
      year: "year",
      color: "color",
      status: "status",
      runningstatus: "runningStatus",
      lastupdated: "lastUpdated",
      deviceimei: "deviceImei",
    },
    export: {
      filename: "vehicles-export",
      headers: [
        "organizationName",
        "vehicleType",
        "vehicleNumber",
        "ais140Compliant",
        "ais140CertificateNumber",
        "make",
        "model",
        "year",
        "color",
        "status",
        "runningStatus",
        "lastUpdated",
        "deviceImei",
      ],
      model: Vehicle,
      populate: [{ path: "organizationId", select: "name" }],
      mapDocument: (doc) => ({
        organizationName: doc.organizationId?.name || "",
        vehicleType: doc.vehicleType || "",
        vehicleNumber: doc.vehicleNumber || "",
        ais140Compliant: doc.ais140Compliant === true ? "true" : "false",
        ais140CertificateNumber: doc.ais140CertificateNumber || "",
        make: doc.make || "",
        model: doc.model || "",
        year: doc.year ?? "",
        color: doc.color || "",
        status: doc.status || "",
        runningStatus: doc.runningStatus || "",
        lastUpdated: doc.lastUpdated ? new Date(doc.lastUpdated).toISOString() : "",
        deviceImei: doc.deviceImei || "",
      }),
    },
  },
  devices: {
    entity: "devices",
    label: "devices",
    importFields: [
      "organizationId",
      "organizationName",
      "imei",
      "softwareVersion",
      "vendorId",
      "deviceModel",
      "manufacturer",
      "simNumber",
      "serialNumber",
      "firmwareVersion",
      "hardwareVersion",
      "warrantyExpiry",
      "status",
      "vehicleRegistrationNumber",
    ],
    requiredFields: ["imei", "softwareVersion"],
    requiredFieldGroups: ["organization"],
    headerAliases: {
      organizationid: "organizationId",
      organizationname: "organizationName",
      imei: "imei",
      softwareversion: "softwareVersion",
      swversion: "softwareVersion",
      vendorid: "vendorId",
      devicemodel: "deviceModel",
      manufacturer: "manufacturer",
      simnumber: "simNumber",
      serialnumber: "serialNumber",
      firmwareversion: "firmwareVersion",
      hardwareversion: "hardwareVersion",
      warrantyexpiry: "warrantyExpiry",
      status: "status",
      vehicleregistrationnumber: "vehicleRegistrationNumber",
    },
    export: {
      filename: "devices-export",
      headers: [
        "organizationName",
        "imei",
        "softwareVersion",
        "vendorId",
        "deviceModel",
        "manufacturer",
        "simNumber",
        "serialNumber",
        "firmwareVersion",
        "hardwareVersion",
        "warrantyExpiry",
        "status",
        "vehicleRegistrationNumber",
      ],
      model: GpsDevice,
      populate: [{ path: "organizationId", select: "name" }],
      mapDocument: (doc) => ({
        organizationName: doc.organizationId?.name || "",
        imei: doc.imei || "",
        softwareVersion: doc.softwareVersion || "",
        vendorId: doc.vendorId || "",
        deviceModel: doc.deviceModel || "",
        manufacturer: doc.manufacturer || "",
        simNumber: doc.simNumber || "",
        serialNumber: doc.serialNumber || "",
        firmwareVersion: doc.firmwareVersion || "",
        hardwareVersion: doc.hardwareVersion || "",
        warrantyExpiry: doc.warrantyExpiry ? new Date(doc.warrantyExpiry).toISOString() : "",
        status: doc.status || "",
        vehicleRegistrationNumber: doc.vehicleRegistrationNumber || "",
      }),
    },
  },
  drivers: {
    entity: "drivers",
    label: "drivers",
    importFields: [
      "organizationId",
      "organizationName",
      "firstName",
      "lastName",
      "email",
      "phone",
      "licenseNumber",
      "licenseExpiry",
      "status",
      "password",
    ],
    requiredFields: ["firstName", "lastName", "email", "phone", "licenseNumber", "password"],
    requiredFieldGroups: ["organization"],
    headerAliases: {
      organizationid: "organizationId",
      organizationname: "organizationName",
      firstname: "firstName",
      lastname: "lastName",
      email: "email",
      phone: "phone",
      mobilenumber: "phone",
      licensenumber: "licenseNumber",
      licenseexpiry: "licenseExpiry",
      status: "status",
      password: "password",
      passwordhash: "password",
    },
    export: {
      filename: "drivers-export",
      headers: [
        "organizationName",
        "firstName",
        "lastName",
        "email",
        "phone",
        "licenseNumber",
        "licenseExpiry",
        "status",
        "createdAt",
      ],
      model: Driver,
      populate: [{ path: "organizationId", select: "name" }],
      mapDocument: (doc) => ({
        organizationName: doc.organizationId?.name || "",
        firstName: doc.firstName || "",
        lastName: doc.lastName || "",
        email: doc.email || "",
        phone: doc.phone || "",
        licenseNumber: doc.licenseNumber || "",
        licenseExpiry: doc.licenseExpiry ? new Date(doc.licenseExpiry).toISOString() : "",
        status: doc.status || "",
        createdAt: doc.createdAt ? new Date(doc.createdAt).toISOString() : "",
      }),
    },
  },
  devicemapping: {
    entity: "devicemapping",
    label: "device mapping",
    importFields: [
      "vehicleNumber",
      "imei",
    ],
    requiredFields: ["vehicleNumber", "imei"],
    requiredFieldGroups: [],
    headerAliases: {
      vehiclenumber: "vehicleNumber",
      registrationnumber: "vehicleNumber",
      registration: "vehicleNumber",
      platenumber: "vehicleNumber",
      imei: "imei",
      deviceimei: "imei",
    },
    export: {
      filename: "device-mapping-export",
      headers: ["vehicleNumber", "imei", "deviceModel", "mappingDate"],
      model: DeviceMapping,
      baseFilter: { unassignedAt: null },
      populate: [
        { path: "vehicleId", select: "vehicleNumber organizationId" },
        { path: "gpsDeviceId", select: "imei deviceModel organizationId" },
      ],
      mapDocument: (doc) => ({
        vehicleNumber: doc.vehicleId?.vehicleNumber || "",
        imei: doc.gpsDeviceId?.imei || "",
        deviceModel: doc.gpsDeviceId?.deviceModel || "",
        mappingDate: doc.assignedAt ? new Date(doc.assignedAt).toISOString() : "",
      }),
    },
  },
  drivermapping: {
    entity: "drivermapping",
    label: "driver mapping",
    importFields: [
      "vehicleNumber",
      "driverEmail",
    ],
    requiredFields: ["vehicleNumber", "driverEmail"],
    requiredFieldGroups: [],
    headerAliases: {
      vehiclenumber: "vehicleNumber",
      registrationnumber: "vehicleNumber",
      registration: "vehicleNumber",
      platenumber: "vehicleNumber",
      driveremail: "driverEmail",
      email: "driverEmail",
    },
    export: {
      filename: "driver-mapping-export",
      headers: ["vehicleNumber", "driverName", "driverEmail", "licenseNumber"],
      model: VehicleDriverMapping,
      baseFilter: { unassignedAt: null, status: "assigned" },
      populate: [
        { path: "vehicleId", select: "vehicleNumber organizationId" },
        { path: "driverId", select: "firstName lastName email phone licenseNumber organizationId" },
      ],
      mapDocument: (doc) => ({
        vehicleNumber: doc.vehicleId?.vehicleNumber || "",
        driverName: [doc.driverId?.firstName, doc.driverId?.lastName].filter(Boolean).join(" "),
        driverEmail: doc.driverId?.email || "",
        driverPhone: doc.driverId?.phone || "",
        licenseNumber: doc.driverId?.licenseNumber || "",
      }),
    },
  },
};

function getEntityConfig(entity) {
  return ENTITY_CONFIGS[entity] || null;
}

function getSupportedEntities() {
  return Object.keys(ENTITY_CONFIGS);
}

module.exports = {
  ENTITY_CONFIGS,
  getEntityConfig,
  getSupportedEntities,
};
